extends GodotGoTest
## Material Maker export loading, against fixture maps generated by
## tools/gen_assets.py rather than a full 2048 px export.

const MAPS_DIR := "res://tests/fixtures/materials/demo"
const EXPORTED_DIR := "res://tests/fixtures/materials/exported"


func test_find_maps_discovers_material_maker_names() -> void:
	var maps := MaterialMakerLoader.find_maps(MAPS_DIR, "demo")
	assert_true(maps.has("albedo_texture"))
	assert_true(maps.has("normal_texture"))
	assert_true(maps.has("emission_texture"))
	assert_true(maps.has("orm"), "a packed ORM map is reported under the orm key")
	assert_false(maps.has("roughness_texture"), "no separate roughness map in this export")


func test_builds_a_material_from_maps_when_no_tres_exists() -> void:
	var material := MaterialMakerLoader.load_material(MAPS_DIR, "demo")
	assert_is(material, StandardMaterial3D)
	assert_not_null(material.albedo_texture)
	assert_true(material.normal_enabled)
	assert_true(material.emission_enabled)
	assert_almost_eq(material.metallic, 1.0, 0.001, "a metallic map drives metallic fully")


func test_orm_map_is_split_across_the_three_channels() -> void:
	var material := MaterialMakerLoader.load_material(MAPS_DIR, "demo")
	assert_eq(material.ao_texture, material.roughness_texture, "one ORM texture feeds all three")
	assert_eq(material.ao_texture, material.metallic_texture)
	assert_eq(material.ao_texture_channel, BaseMaterial3D.TEXTURE_CHANNEL_RED)
	assert_eq(material.roughness_texture_channel, BaseMaterial3D.TEXTURE_CHANNEL_GREEN)
	assert_eq(material.metallic_texture_channel, BaseMaterial3D.TEXTURE_CHANNEL_BLUE)
	assert_true(material.ao_enabled)


func test_an_exported_tres_wins_over_the_maps() -> void:
	var material := MaterialMakerLoader.load_material(EXPORTED_DIR, "exported")
	assert_not_null(material)
	assert_eq(material.resource_name, "ExportedFixture")


func test_material_name_defaults_to_the_directory_name() -> void:
	var material := MaterialMakerLoader.load_material(EXPORTED_DIR)
	assert_eq(material.resource_name, "ExportedFixture")


func test_a_missing_directory_yields_a_plain_material() -> void:
	var material := MaterialMakerLoader.load_material("res://tests/fixtures/materials/absent")
	assert_is(material, StandardMaterial3D)
	assert_null(material.albedo_texture)
	assert_false(material.normal_enabled)
	assert_false(material.emission_enabled)


func test_orm_never_overrides_a_separately_exported_map() -> void:
	var material := StandardMaterial3D.new()
	var separate := ImageTexture.create_from_image(Image.create(2, 2, false, Image.FORMAT_RGB8))
	var orm := ImageTexture.create_from_image(Image.create(2, 2, false, Image.FORMAT_RGB8))
	material.roughness_texture = separate
	MaterialMakerLoader._apply_orm(material, orm)
	assert_eq(material.roughness_texture, separate)
	assert_eq(material.metallic_texture, orm)


func test_heightmap_accepts_both_material_maker_spellings() -> void:
	var candidates: Array = MaterialMakerLoader.MAP_CANDIDATES["heightmap_texture"]
	assert_true(candidates.has("%s_heightmap.png"))
	assert_true(candidates.has("%s_height.png"))
