#!/usr/bin/env bash
# Scaffold a new Godot game in games/<slug> from templates/<template>.
#
# Usage: tools/new_game.sh <slug> [--title "Nice Name"] [--desc "One line"]
#                                 [--template blank]
#
# The new project is wired to the shared framework (addons/godotgo is symlinked
# to framework/addons/godotgo), gets fresh resource UIDs, and is verified with
# tools/check.sh + tools/test.sh before the script returns.
set -o pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$GODOTGO_ROOT"

slug="${1:-}"
shift || true
template="blank"
title=""
desc=""
while [ $# -gt 0 ]; do
	case "$1" in
		--title) title="$2"; shift 2 ;;
		--desc) desc="$2"; shift 2 ;;
		--template) template="$2"; shift 2 ;;
		*) echo "unknown option: $1" >&2; exit 2 ;;
	esac
done

if [[ ! "$slug" =~ ^[a-z][a-z0-9-]*$ ]]; then
	echo "usage: tools/new_game.sh <slug> [--title T] [--desc D] [--template blank]" >&2
	echo "  slug must be lower-case letters, digits and dashes" >&2
	exit 2
fi
dest="games/$slug"
[ -e "$dest" ] && { echo "$dest already exists" >&2; exit 2; }
[ -d "templates/$template" ] || { echo "no template '$template' in templates/" >&2; exit 2; }

# Title-case the slug when no title is given: "space-race" -> "Space Race".
if [ -z "$title" ]; then
	title="$(echo "$slug" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
fi
[ -z "$desc" ] && desc="A GodotGo sample game."

echo "==> creating $dest from templates/$template"
mkdir -p "$dest"
cp -R "templates/$template/." "$dest/"
mkdir -p "$dest/addons"
ln -sfn ../../../framework/addons/godotgo "$dest/addons/godotgo"
# The template's project.godot already enables Godot AI, so link it in too when
# this machine has it; without the link that enable line is a dangling
# reference the editor complains about. Both are gitignored.
if [ -f "$GODOTGO_ROOT/vendor/godot_ai/plugin.cfg" ]; then
	ln -sfn ../../../vendor/godot_ai "$dest/addons/godot_ai"
	godotgo_set_editor_plugin "$dest/project.godot" "res://addons/godot_ai/plugin.cfg" on
fi

# Fresh UIDs, generated by Godot rather than invented.
uid_main="$(tools/godot.sh --headless --path framework \
	--script res://addons/godotgo/tools/new_uid.gd 2>/dev/null | grep '^uid://' | head -1)"
uid_hud="$(tools/godot.sh --headless --path framework \
	--script res://addons/godotgo/tools/new_uid.gd 2>/dev/null | grep '^uid://' | head -1)"
if [ -z "$uid_main" ] || [ -z "$uid_hud" ] || [ "$uid_main" = "$uid_hud" ]; then
	echo "could not generate two distinct resource UIDs" >&2
	exit 1
fi

while IFS= read -r f; do
	python3 - "$f" "$title" "$desc" "$slug" "$uid_main" "$uid_hud" <<'PY'
import sys
path, title, desc, slug, uid_main, uid_hud = sys.argv[1:7]
with open(path, encoding="utf-8") as fh:
    text = fh.read()
for token, value in (
    ("__GAME_TITLE__", title),
    ("__GAME_DESC__", desc),
    ("__GAME_SLUG__", slug),
    ("__UID_MAIN__", uid_main),
    ("__UID_HUD__", uid_hud),
):
    text = text.replace(token, value)
with open(path, "w", encoding="utf-8") as fh:
    fh.write(text)
PY
done < <(find "$dest" -type f \( -name '*.gd' -o -name '*.tscn' -o -name '*.tres' -o -name '*.godot' -o -name '*.md' \))

echo "==> verifying"
tools/check.sh "$slug" || exit 1
tools/test.sh "$slug" || exit 1
tools/smoke.sh "$slug" || exit 1

cat <<MSG

Created $dest
  tools/run.sh $slug          play it
  tools/verify.sh $slug       check, test and smoke it
  \$EDITOR $dest/scripts/game.gd   the session subclass where rules live
MSG
